version: '0.1'
services:
  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PSSWD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_USER_PSSWD