INSERT INTO item_category (name, description) VALUES ("armor", "");
INSERT INTO item_category (name, description) VALUES ("weapon", "");
INSERT INTO item_category (name, description) VALUES ("key", "");
INSERT INTO item_category (name, description) VALUES ("wand", "");
INSERT INTO item_category (name, description) VALUES ("potion", "");
INSERT INTO item_category (name, description) VALUES ("other", "");
INSERT INTO game (name) VALUES ("pixel dungeon");
INSERT INTO user_type (name) VALUES ("user");
INSERT INTO user_type (name) VALUES ("admin");
INSERT INTO user_type (name) VALUES ("developer");
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("battle axe","This is a crude and heavy weapon. It's specifically designed todeal devastating blows to your enemies.", 2, 1, 1, 23, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("dagger","A well balanced dagger. Sharp and short for dealing fast and effective blows to unsuspecting foes.", 2, 1, 2, 20, 10);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("glaive","A bladed staff weapon. This long weapon is an effective tool for keeping your foes in a distance and deal slashing hits.", 2, 1, 3, 31, 50);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("brass knuckles","Piece of metal designed to fit around the fingers and gripped by the hand. Increases your punching power dramatically.", 2, 1, 4, 17, 10);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("longsword","Widely-used standard straight sword. An accessible sword which inflicts consistent regular damage and high slash damage, making it applicable to avariety of situations.", 2, 1, 5, 21, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("mace","The iron head of this weapon inflicts substantial damage", 2, 1, 6, 19, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("quarterstaff","A staff of hardwood, its ends are shod with iron", 2, 1, 7, 16, 20);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("shortsword","It is indeed quite short, just a few inches longer, than a dagger", 2, 1, 8, 3, 10);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("spear","A slender wooden rod tipped with sharpened iron", 2, 1, 9, 30, 20);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("greatsword","Greatswords are powerful blades with a wide swing radius and long reaching attacks, enabling the wielder to target multiple opponents within theradius of the swing motion.", 2, 1, 10, 22, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("war hammer","Few creatures can withstand the crushing blow of this towering mass of lead and steel, but only the strongest of adventurers can use it effectively.", 2, 1, 11, 24, 50);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("cloth armor","This lightweight armor offers basic protection.", 1, 1, 12, 25, 10);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("leather armor","Armor made from tanned monster hide. Not as light as cloth armor but provides better protection.", 1, 1, 13, 26, 20);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("mail armor","Interlocking metal links make for a tough but flexible suit of armor.", 1, 1, 14, 27, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("plate armor","Enormous plates of metal are joined together into a suit thatprovides unmatched protection to any adventurer strong enough to bear its staggering weight.", 1, 1, 15, 28, 50);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("scale armor","The metal scales sewn onto a leather vest create a flexible, yet protective armor.", 1, 1, 16, 29, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("golden key","The notches on this golden key are tiny and intricate. Maybe it can open some chest lock?", 3, 1, 17, 11, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("iron key","This iron key is small and simple. Maybe it can open some door?", 3, 1, 18, 10, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("skeleton key","This key looks serious: its head is shaped like a skull. Probably it can open some serious door.", 3, 1, 19, 9, 30);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of amok","The purple light from this wand will make the target run amokattacking random creatures in its vicinity.", 4, 1, 20, 4, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of avalanche","When a discharge of this wand hits a wall (or any other solidobstacle) it causes an avalanche of stones, damaging and stunning all creatures in the affected area.", 4, 1, 21, 49, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of blink","This wand will allow you to teleport in the chosen direction.Creatures and inanimate obstructions will block the teleportation.", 4, 1, 22, 50, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of disintegration","This wand emits a beam of destructive energy, which pierces all creatures in its way. The more targets it hits, the more damage it inflicts to each of them.", 4, 1, 23, 51, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of firebolt","This wand unleashes bursts of magical fire. It will ignite flammable terrain, and will damage and burn a creature it hits.", 4, 1, 24, 52, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of flock","A flick of this wand summons a flock of magic sheep, creatingtemporary impenetrable obstacle.", 4, 1, 25, 53, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of lightning","This wand conjures forth deadly arcs of electricity, which deal damage to several creatures standing close to each other.", 4, 1, 26, 54, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of magic missile","This wand launches missiles of pure magical energy, dealing moderate damage to a target creature.", 4, 1, 27, 55, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of poison","The vile blast of this twisted bit of wood will imbue its target with a deadly venom. A creature that is poisoned will suffer periodic damageuntil the effect ends. The duration of the effect increases with the level of the staff.", 4, 1, 28, 56, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of reach","This utility wand can be used to grab objects from a distanceand to switch places with enemies. Waves of magic force radiated from it will affect all cells on their way triggering traps, trampling high vegetation, opening closed doors and closing open ones.", 4, 1, 29, 69, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of regrowth",""When life ceases new life always begins to grow... The eternal cycle always remains!"", 4, 1, 30, 70, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of slowness","This wand will cause a creature to move and attack at half its ordinary speed until the effect ends", 4, 1, 31, 71, 40);
INSERT INTO item_inventory (quantity) VALUES (100);
INSERT INTO item (name, description, category_id, game_id, inventory_id, path_to_image, price) VALUES ("wand of teleportation","A blast from this wand will teleport a creature against its will to a random place on the current level.", 4, 1, 32, 72, 40);
